name: Pages

on:
  push:
    branches:
      - main # default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
          fetch-depth: '0'
      - name: Restore file modification time
        run: |
          git config --global core.quotepath false
          git ls-files --directory source | while read path; do touch -d "$(git log -1 --format='@%ct' $path)" "$path"; done
      # 使用npm安装依赖
      - uses: pnpm/action-setup@v3
        with:
          version: 10.6.3
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'
      - name: Install Dependencies
        run: pnpm install
      # 步骤 5：部署到 GitHub Pages (部署到 gh-pages 分支)
      - name: Deploy to GitHub Pages # 使用 Hexo 部署到 GitHub Pages
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE }} # 使用 GitHub Secrets 中存储的 SSH 私钥
          GIT_NAME: xu756 # Git 用户名
          GIT_EMAIL: 756334744@qq.com # Git 用户邮箱
        run: |
          mkdir -p ~/.ssh/                              # 创建 SSH 配置目录
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa  # 将私钥写入文件
          chmod 600 ~/.ssh/id_rsa                       # 设置私钥权限
          ssh-keyscan github.com >> ~/.ssh/known_hosts  # 添加 GitHub 的 SSH 公钥到 known_hosts
          git config --global user.name "$GIT_NAME"     # 配置 Git 用户名
          git config --global user.email "$GIT_EMAIL"    # 配置 Git 用户邮箱
          # git ls-files -z | xargs -0 -I {} bash -c 'ts=$(git log -1 --format="@%ct" -- "{}" 2>/dev/null); [ -n "$ts" ] && touch -d "$ts" "{}"'
          pnpm hexo clean
          pnpm hexo bangumi -u
          pnpm hexo deploy                                   # 使用 Hexo 部署博客
          pnpm hexo algolia
