name: Pages

on:
  push:
    branches:
      - main # default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
      # 使用npm安装依赖
      - uses: pnpm/action-setup@v2
        with:
          version: 10.6.3
      - name: 显示source/_posts 所有文件的更新时间
        run: find source/_posts -type f -name "*.md" -exec stat -f "%Sm %N" -t "%Y-%m-%d %H:%M:%S" {} + | sort -r
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'
      - name: Install Dependencies
        run: pnpm install
      - name: bangumi
        run: pnpm hexo bangumi -u
      - name: Build
        run: pnpm run build

      - name: algolia
        run: pnpm hexo algolia
      - name: Git配置邮箱
        run: |
          git config --global user.email "756334744@qq.com"
          git config --global user.name "xu756"
          git config --global user.password ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        run: pnpm run deploy
